### PR TITLE
Sidebar no longer stays collapsed until all js has been loaded in.

### PR DESCRIPTION
**Pull request by Daniel-I-Am**
A suggested fix for #27.

### CODE REVIEW

**Comment by Lucky-Loek** [comment]
Thanks! I was already working on this with complete client-side functionality (so no cookies and the like). I don't think it should be the responsibility of the server-side code to show the correct menu bar.

Leaving this open for now because I expect I can fix this the "correct" way this week.

**Comment by Daniel-I-Am** [comment]
I'd rather do this front-end as well. Problem with that is that it needs to wait until the file is loaded in.
You would most likely still get the same result. If you optimize it, it may be less noticeable, but on a slow connection it will still be visible.

**Comment by BackEndTea** [comment]
> I don't think it should be the responsibility of the server-side code to show the correct menu bar.

🤔

**Comment by Lucky-Loek** [comment]
Fixed with client-side solution in v2.7.1

Many thanks for the work though!

**Pull request closed without merging**
