### PR TITLE
Stop my email from changing in other packages

### PR DESCRIPTION
**Pull request by BackEndTea**
See: https://github.com/composer/composer/issues/8060#issuecomment-476648723

### CODE REVIEW

**Comment by Lucky-Loek** [comment]
Changes one line of configuration code in the project.

Needs to open a new PR because Composer screws up his email address.

The irony 😆

**Comment by BackEndTea** [comment]
Can you tag a new release so my email updates again in every package that has been updated in the mean time? I need the exposure

**Comment by Lucky-Loek** [comment]
I'll cherrypick every commit from now on. Exposure denied.

**Comment by Lucky-Loek** [comment]
Fixed in v2.3.1 though. Morality got the best of me.

**Pull request merged**
